Repository sikaozhe1997/Xin-Yue, pull requests merged in 2018-04, with the labels that each got.

#577 修改备注
  23日晚匿名者声援岳昕字报.md
Labels: lgtm

#289 Fix typos
  letter.md
Labels: lgtm

#565 add this link to bitcoin cash blockchain
  README.md
Labels: lgtm

#553 Link Checker with Travis
  .travis.yml
  README.md
  check_links.sh
Labels: lgtm

#581 根据 #542 更新一些issue模板
  .github/ISSUE_TEMPLATE.md
  ISSUE_TEMPLATE.md
Labels: wip

#616 添加issues template 内容。
  .github/ISSUE_TEMPLATE.md
Labels: lgtm

#634 增加gitignore
  .gitignore
  docs/.gitignore
  docs/Gemfile
  docs/_config.yml
  docs/index.md
Labels: lgtm

#626 Update README.md
  README.md
  岳昕：致北京大学师生和北大外国语学院的一封公开信
Labels: enhancement, lgtm

#651 Add prof.彭錞's 约谈是个什么东西.
  README.md
  约谈是个什么东西.md
Labels: lgtm

#653 update 沈岿：《学校约谈指南》第三稿及修改说明
  README.md
  沈岿：《学校约谈指南》.md
  沈岿：《学校约谈指南》（建议，第二稿）.md
Labels: lgtm

#661 添加中国青年报的评论报道
  问诊高校信息公开-中国青年报-20170426期第5版.md
Labels: lgtm

#707 添加评论文章：我所认识的木田同学
  README.md
  我所认识的木田同学.md
  沈阳事件.md
Labels: lgtm

#712 add 《岳昕：新年献词 | 2017的三个追问》
  README.md
  岳昕：新年献词--2017的三个追问.md
Labels: lgtm
